### ISSUE TITLE
Hilos Consola

### ISSUE THREAD

**Issue by Kevinosorio77** [SistemasTecTlaxiaco/actividad-8-practica-de-hilos-de-consola-equipo-kem#1]
[PRACTICAS DE HILOS.pdf](https://github.com/SistemasTecTlaxiaco/actividad-8-practica-de-hilos-de-consola-equipo-kem/files/15133173/PRACTICAS.DE.HILOS.pdf)

**Comment by IrvinSanchez-dev** [comment]
DADO A LA RUBRICA DE EVALUACION OBTUVIERON UN 19%

**LES HIZO FALTA MAS IMAGENES, EL TOTAL ERA 20 Y SOLO PUSIERON 15.

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
